### ISSUE TITLE
Build fails: Rollup failed to resolve import "linkedom"

### ISSUE THREAD

**Issue by bennihtm** [delucis/astro-embed#109]
I updated to version 0.7.0 and now the build of my site fails with the following error: ``Rollup failed to resolve import "linkedom"``.
The dev server with ``pnpm dev`` still works fine.

I looked up the error and couldn't find a solution. My project is at https://github.com/bennihtm/astro-blog and the PR that broke stuff is [here](https://github.com/bennihtm/astro-blog/pull/97).

```
> astro build

13:35:40 [vite] Re-optimizing dependencies because lockfile has changed
13:35:42 [build] output: "static"
13:35:42 [build] directory: C:\Users\Benni\Documents\astro-blog\dist\
13:35:42 [build] Collecting build info...
13:35:42 [build] ✓ Completed in 2.98s.
13:35:42 [build] Building static entrypoints...
13:35:48 [ERROR] [vite] x Build failed in 5.66s
13:35:48 [astro-icon] Loaded icons from src/icons
[vite]: Rollup failed to resolve import "linkedom" from "C:/Users/Benni/Documents/astro-blog/node_modules/.pnpm/@astro-community+astro-embed-utils@0.1.1/node_modules/@astro-community/astro-embed-utils/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
  Stack trace:
    at viteWarn (file:///C:/Users/Benni/Documents/astro-blog/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67432:27)
    at onwarn (file:///C:/Users/Benni/Documents/astro-blog/node_modules/.pnpm/vite@5.2.7/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:67164:13)
    at Object.logger [as onLog] (file:///C:/Users/Benni/Documents/astro-blog/node_modules/.pnpm/rollup@4.13.2/node_modules/rollup/dist/es/shared/node-entry.js:19983:9)
    at file:///C:/Users/Benni/Documents/astro-blog/node_modules/.pnpm/rollup@4.13.2/node_modules/rollup/dist/es/shared/node-entry.js:18883:26
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by delucis** [comment]
Ahhh, I bet we forgot to add it as a dependency in #73 — it’s already used elsewhere in the monorepo, so I guess npm didn’t throw any errors.

**Comment by delucis** [comment]
Yes indeed — we’d forgotten to add it to `package.json` for `@astro-community/astro-embed-utils`. Could you try updating again? You might need to use `@dependabot recreate` in your failing PR to get it to regenerate it from scratch or alternatively manually run `pnpm update @astro-community/astro-embed-utils` to pull in the fixed dependency.

**Comment by bennihtm** [comment]
It works now! Thank you!

**Comment by delucis** [comment]
Awesome — thanks for confirming!
